import { clsx, type ClassValue } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

// tailwind-merge no conoce la escala del sistema. Sin esto toma `text-meta` por
// un color y lo borra cuando al lado hay un `text-ink`: es lo que pasaba en
// creativos, donde varios componentes pedían un tamaño que nunca llegaba.
const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      color: [
        "white",
        "black",
        "paper",
        "paper-raised",
        "paper-sunken",
        "paper-sunken-hover",
        "paper-shade",
        "ink",
        "ink-hover",
        "ink-press",
        "ink-2",
        "ink-3",
        "ink-4",
        "rule",
        "rule-strong",
        "stage",
        "stage-raised",
        "stage-rule",
        "stage-ink",
        "stage-3",
        "stage-scroll",
        "ember",
        "ember-deep",
        "ember-soft",
        "ember-light",
        "pass",
        "pass-rule",
        "pass-wash",
        "pass-soft",
        "fail",
        "fail-rule",
        "fail-wash",
        "fail-wash-hover",
        "fail-soft",
        "warn",
        "warn-rule",
        "warn-wash",
        "warn-soft",
        "dato-1",
        "dato-2",
        "dato-3",
        "dato-4",
        "dato-5",
        "dato-6",
        "dato-1-soft",
        "dato-2-soft",
        "dato-3-soft",
        "dato-4-soft",
        "dato-5-soft",
        "dato-6-soft",
      ],
      text: ["nano", "micro", "meta", "base", "lede", "h3", "h2", "h1", "display"],
      radius: ["chip", "control", "control-inner", "panel", "sheet"],
      shadow: [
        "hair",
        "card",
        "card-lift",
        "lift",
        "sheet",
        "piece",
        "piece-lift",
        "rail",
        "studio",
        "bevel",
      ],
      font: ["display", "sans", "mono"],
    },
  },
});

export const cn = (...i: ClassValue[]) => twMerge(clsx(i));
